# Generated by Django 5.1.6 on 2025-02-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catName', models.CharField(max_length=100)),
                ('catCode', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemName', models.CharField()),
                ('itemCode', models.CharField(primary_key=True, serialize=False)),
                ('catName', models.CharField()),
            ],
        ),
    ]
