# Generated by Django 5.1.6 on 2025-02-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catName', models.CharField(max_length=100)),
                ('catCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemName', models.CharField(max_length=100)),
                ('itemCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('catName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsAndItems.category')),
            ],
        ),
    ]
