# Generated by Django 5.1.6 on 2025-02-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsAndItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catCode',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemCode',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(),
        ),
    ]
