# Generated by Django 5.1.6 on 2025-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsAndItems', '0002_alter_category_catcode_alter_item_itemcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catName',
            field=models.CharField(),
        ),
    ]
