# Generated by Django 5.1.6 on 2025-03-03 19:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ET')),
                ('faydaNumber', models.CharField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
