# Generated by Django 5.1.6 on 2025-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addresId', models.CharField(primary_key=True, serialize=False)),
                ('addresName', models.CharField()),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField()),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
