# Generated by Django 5.1.6 on 2025-02-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addresId', models.CharField(primary_key=True, serialize=False)),
                ('addresName', models.CharField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
