# Generated by Django 5.1.6 on 2025-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='addresId',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
