# Generated by Django 5.1.6 on 2025-02-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodsAndItems', '0003_alter_item_catname'),
        ('locationManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('shipId', models.CharField(editable=False, max_length=255, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsAndItems.item')),
                ('location1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location1_set', to='locationManagement.address')),
                ('location2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location2_set', to='locationManagement.address')),
            ],
        ),
    ]
