# Generated by Django 5.1.6 on 2025-03-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('locationManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('item', models.CharField()),
                ('description', models.TextField()),
                ('distance', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('shipId', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('onshipping', 'On Shipping'), ('delivered', 'Delivered'), ('onreviewing', 'On Reviewing'), ('reviewed', 'Reviewed'), ('pending', 'Pending')], default='onreviewing', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('location1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders_from', to='locationManagement.address')),
                ('location2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders_to', to='locationManagement.address')),
            ],
        ),
    ]
