# Generated by Django 5.1.6 on 2025-02-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('goodsAndItems', '0001_initial'),
        ('locationManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('distance', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('shipId', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsAndItems.item')),
                ('location1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders_from', to='locationManagement.address')),
                ('location2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders_to', to='locationManagement.address')),
            ],
        ),
    ]
