# Generated by Django 5.1.6 on 2025-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='shipId',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
