# Generated by Django 5.1.6 on 2025-02-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postManagement', '0002_alter_shippingorder_shipid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingorder',
            name='item',
        ),
    ]
