# Generated by Django 5.1.6 on 2025-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsAndItems', '0001_initial'),
        ('postManagement', '0003_remove_shippingorder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='item',
            field=models.ManyToManyField(related_name='shipping_orders', to='goodsAndItems.item'),
        ),
    ]
